### ISSUE TITLE
specsavers.find is failing

### ISSUE THREAD

**Issue by alxwrd** [alxwrd/specsavers#3]
```python
>>> import specsavers
>>> notts = specsavers.find("nottingham")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexwar/.local/lib/python3.6/site-packages/specsavers/__init__.py", line
12, in find
    return Store(store_name)
  File "/home/alexwar/.local/lib/python3.6/site-packages/specsavers/store.py", line 22, in __init__
    self.json = self.__fetch_store_details()
  File "/home/alexwar/.local/lib/python3.6/site-packages/specsavers/store.py", line 62, in __fetch_store_details
    stores = details.get("content", {}).get("stores", [])
AttributeError: 'list' object has no attribute 'get'
```

**Comment by alxwrd** [comment]
I just checked this and it worked fine 😅
